### PR TITLE
Fixing wrong wording for source branch

### PR DESCRIPTION
**Pull request by daniel-sc**

### CODE REVIEW

**Review by robertodr — COMMENTED** [review]
Thanks for your PR. I agree that the wording here is confusing and should be changed. We meant that whereas you need to have the PR from any fork based off the target branch, you should commit your work to a separate branch, as to avoid the scenario documented [here](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)

This is what we had in mind. Say you are working on a new feature that should land on `master`:
1. You create a fork of the canonical repo.
2. You branch off of `master` the branch `new-feature`.
3. Commit to `new-feature` and push.
4. Open a PR. This will target `canonical:master` from `your-fork:new-feature` rather than being `canonical:master` from `your-fork:master`.

**Comment by daniel-sc** [comment]
I understand, probably one should clarify that 

1. The new branch should _start off_ from the target branch. 
2. The _naming_ of the new branch should follow feature/issue branch naming conventions.

Would this distinction bewteen naming and starting point resolve this ambiguity?

**Comment by robertodr** [comment]
Yes, that would do it, in conjunction with a link to that blog posts which explains why creating a new branch is a good idea.

**Review by robertodr — APPROVED** [review]
Thank you! Waiting for @bast to also read through the change before merging.

**Comment by bast** [comment]
Thanks so much!

**Pull request merged**
